In [42]:
import pandas as pd

# reading a csv file
df = pd.read_csv('BankChurners.csv') 
# Dropping unnecessary columns
df = df.drop(columns=['CLIENTNUM','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'])

In [43]:
# Displaying the count of each category for all categorical columns
for i in df.select_dtypes(include = 'object').columns:
    print(df.groupby(by = [i])[i].count())
    print("\n")

Attrition_Flag
Attrited Customer    1627
Existing Customer    8500
Name: Attrition_Flag, dtype: int64


Gender
F    5358
M    4769
Name: Gender, dtype: int64


Education_Level
College          1013
Doctorate         451
Graduate         3128
High School      2013
Post-Graduate     516
Uneducated       1487
Unknown          1519
Name: Education_Level, dtype: int64


Marital_Status
Divorced     748
Married     4687
Single      3943
Unknown      749
Name: Marital_Status, dtype: int64


Income_Category
$120K +            727
$40K - $60K       1790
$60K - $80K       1402
$80K - $120K      1535
Less than $40K    3561
Unknown           1112
Name: Income_Category, dtype: int64


Card_Category
Blue        9436
Gold         116
Platinum      20
Silver       555
Name: Card_Category, dtype: int64

In [ ]:
# Creating 4 seperate columns from the card_category column
df = pd.get_dummies(df, columns=['Card_Category'], prefix='', prefix_sep='')

# Converting the newly created columns to integers
for col in ['Blue','Silver', 'Gold', 'Platinum']:
    if col in df.columns:
        df[col] = df[col].astype(int)

# Rearranging the columns for clarity
columns_order = [col for col in ['Blue',  'Silver','Gold', 'Platinum'] if col in df.columns] + \
                [col for col in df.columns if col not in ['Blue','Silver', 'Gold', 'Platinum']]
df = df[columns_order]

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attrition_Flag            10127 non-null  object
 1   Customer_Age              10127 non-null  int64
 2   Gender                    10127 non-null  object
 3   Dependent_count           10127 non-null  int64
 4   Education_Level           10127 non-null  object
 5   Marital_Status            10127 non-null  object
 6   Income_Category           10127 non-null  object
 7   Months_on_book            10127 non-null  int64
 8   Total_Relationship_Count  10127 non-null  int64
 9   Months_Inactive_12_mon    10127 non-null  int64
 10  Contacts_Count_12_mon     10127 non-null  int64
 11  Credit_Limit              10127 non-null  float64
 12  Total_Revolving_Bal       10127 non-null  int64
 13  Avg_Open_To_Buy           10127 non-null  float64
 14  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 15  Total_Trans_Amt           10127 non-null  int64
 16  Total_Trans_Ct            10127 non-null  int64
 17  Total_Ct_Chng_Q4_Q1       10127 non-null  float64
 18  Avg_Utilization_Ratio     10127 non-null  float64
 19  Blue                      10127 non-null  int32
 20  Gold                      10127 non-null  int32
 21  Platinum                  10127 non-null  int32
 22  Silver                    10127 non-null  int32
dtypes: float64(5), int32(4), int64(9), object(5)
memory usage: 1.6+ MB
None

In [32]:
df.describe()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Blue,Gold,Platinum,Silver
count,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000
mean,46.325960,2.346203,35.928409,3.812580,2.341167,2.455317,8631.953698,1162.814061,7469.139637,0.759941,4404.086304,64.858695,0.712222,0.274894,0.931767,0.011455,0.001975,0.054804
std,8.016814,1.298908,7.986416,1.554408,1.010622,1.106225,9088.776650,814.987335,9090.685324,0.219207,3397.129254,23.472570,0.238086,0.275691,0.252159,0.106416,0.044398,0.227608
min,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2555.000000,359.000000,1324.500000,0.631000,2155.500000,45.000000,0.582000,0.023000,1.000000,0.000000,0.000000,0.000000
50%,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4549.000000,1276.000000,3474.000000,0.736000,3899.000000,67.000000,0.702000,0.176000,1.000000,0.000000,0.000000,0.000000
75%,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11067.500000,1784.000000,9859.000000,0.859000,4741.000000,81.000000,0.818000,0.503000,1.000000,0.000000,0.000000,0.000000
max,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.999000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# Group by 'Card_Category' and aggregate only numeric columns
grouped_df = (
    df.groupby('Income_Category')
    .mean(numeric_only=True)  # Ensures only numeric columns are used
    .reset_index()
)

# Select the desired columns using a list
selected_columns = ['Income_Category', 'Total_Trans_Amt']
result_df = grouped_df[selected_columns]

result_df

  Income_Category  Total_Trans_Amt
0         $120K +      4529.467675
1     $40K - $60K      4405.618994
2     $60K - $80K      4450.712553
3    $80K - $120K      4482.960261
4  Less than $40K      4363.420107
5         Unknown      4282.211331

In [ ]:
grouped_df1 = (
    df.groupby('Income_Category')
    .mean(numeric_only=True)  # Ensures only numeric columns are used
    .reset_index()
)

selected_columns = ['Income_Category', 'Total_Trans_Amt','Blue','Silver','Gold','Platinum']
result_df = grouped_df1[selected_columns]

result_df

  Income_Category  Total_Trans_Amt      Blue    Silver      Gold  Platinum
0         $120K +      4529.467675  0.887208  0.082531  0.024759  0.005502
1     $40K - $60K      4405.618994  0.935754  0.055307  0.008380  0.000559
2     $60K - $80K      4450.712553  0.907989  0.068474  0.020685  0.002853
3    $80K - $120K      4482.960261  0.908795  0.076221  0.013681  0.001303
4  Less than $40K      4363.420107  0.955630  0.036507  0.006740  0.001123
5         Unknown      4282.211331  0.939748  0.047662  0.008094  0.004496

In [35]:
atrition_mapping = {
    "Attrited Customer":0,
    "Existing Customer":1
}

df['Attrition_Flag'] = df['Attrition_Flag'].map(atrition_mapping)
df['Attrition_Flag'] = df['Attrition_Flag'].astype(float)

In [ ]:
# Filtering out records with utilization ratio less than or equal to 0.05 and calculate their Total_Trans_Amt and  Total_Trans_Ct -->

# Filter records where Avg_Utilization_Ratio is less than or equal to 0.05
filtered_df = df[df['Avg_Utilization_Ratio'] <= 0.05]

# # Calculate the total for Total_Trans_Amt and Total_Trans_Ct
total_trans_amt = filtered_df['Total_Trans_Amt'].sum()
total_trans_ct = filtered_df['Total_Trans_Ct'].sum()

print("Total Transaction Amount (Total_Trans_Amt):", total_trans_amt)
print("Total Transaction Count (Total_Trans_Ct):", total_trans_ct)

Total Transaction Amount (Total_Trans_Amt): 12780794
Total Transaction Count (Total_Trans_Ct): 187936

In [46]:
# Filtering out records with utilization ratio greater than 0.05 and calculate their Total_Trans_Amt and  Total_Trans_Ct -->
# Filter records where Avg_Utilization_Ratio is greater than 0.05
majority_filtered_df = df[df['Avg_Utilization_Ratio'] > 0.05]

# # Calculate the total for Total_Trans_Amt and Total_Trans_Ct
total_trans_amt = majority_filtered_df['Total_Trans_Amt'].sum()
total_trans_ct = majority_filtered_df['Total_Trans_Ct'].sum()

print("Total Transaction Amount (Total_Trans_Amt):", total_trans_amt)
print("Total Transaction Count (Total_Trans_Ct):", total_trans_ct)

Total Transaction Amount (Total_Trans_Amt): 31718850
Total Transaction Count (Total_Trans_Ct): 467522

In [37]:
df.describe()

,Attrition_Flag,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Blue,Gold,Platinum,Silver
count,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000
mean,0.839340,46.325960,2.346203,35.928409,3.812580,2.341167,2.455317,8631.953698,1162.814061,7469.139637,0.759941,4404.086304,64.858695,0.712222,0.274894,0.931767,0.011455,0.001975,0.054804
std,0.367235,8.016814,1.298908,7.986416,1.554408,1.010622,1.106225,9088.776650,814.987335,9090.685324,0.219207,3397.129254,23.472570,0.238086,0.275691,0.252159,0.106416,0.044398,0.227608
min,0.000000,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2555.000000,359.000000,1324.500000,0.631000,2155.500000,45.000000,0.582000,0.023000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4549.000000,1276.000000,3474.000000,0.736000,3899.000000,67.000000,0.702000,0.176000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11067.500000,1784.000000,9859.000000,0.859000,4741.000000,81.000000,0.818000,0.503000,1.000000,0.000000,0.000000,0.000000
max,1.000000,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.999000,1.000000,1.000000,1.000000,1.000000

In [38]:
filtered_df.describe()

,Attrition_Flag,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Blue,Gold,Platinum,Silver
count,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000,2996.000000
mean,0.672897,46.179239,2.390187,35.860147,3.696929,2.401535,2.566756,11688.266422,178.295060,11509.971362,0.741675,4265.952603,62.728972,0.678692,0.006242,0.882844,0.019359,0.004005,0.093792
std,0.469233,7.746241,1.286747,7.814169,1.561517,1.001494,1.127831,11703.945157,418.287398,11420.798362,0.210412,3246.484445,23.168973,0.233808,0.014175,0.321660,0.137807,0.063171,0.291587
min,0.000000,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,1438.300000,0.000000,510.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,41.000000,2.000000,32.000000,3.000000,2.000000,2.000000,2209.000000,0.000000,2209.000000,0.619000,2200.750000,43.000000,0.543000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,46.000000,2.000000,36.000000,4.000000,2.000000,3.000000,5858.500000,0.000000,5858.500000,0.730000,3676.500000,64.000000,0.676000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,51.000000,3.000000,40.000000,5.000000,3.000000,3.000000,19030.500000,0.000000,18734.000000,0.854000,4697.000000,78.000000,0.800000,0.000000,1.000000,0.000000,0.000000,0.000000
max,1.000000,65.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,1702.000000,34516.000000,3.397000,17258.000000,139.000000,3.250000,0.049000,1.000000,1.000000,1.000000,1.000000

In [39]:
majority_filtered_df.describe()

,Attrition_Flag,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Blue,Gold,Platinum,Silver
count,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000,7108.000000
mean,0.909257,46.394766,2.327518,35.957935,3.861424,2.316123,2.407006,7293.371117,1577.630979,5715.740138,0.767903,4462.415588,65.774057,0.726565,0.388857,0.953292,0.008160,0.000985,0.037563
std,0.287263,8.130949,1.303929,8.063335,1.549180,1.012701,1.093461,7292.224663,539.635399,7196.467063,0.222465,3455.454053,23.531540,0.238676,0.254223,0.211027,0.089969,0.031368,0.190151
min,0.000000,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,168.000000,3.000000,0.000000,563.000000,11.000000,0.000000,0.051000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2602.000000,1175.000000,937.750000,0.635000,2141.000000,46.000000,0.596000,0.153000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4180.500000,1567.000000,2651.500000,0.740500,3972.000000,68.000000,0.711000,0.345000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,9149.000000,1974.000000,7599.750000,0.862000,4755.000000,81.000000,0.826000,0.603000,1.000000,0.000000,0.000000,0.000000
max,1.000000,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,32759.000000,3.355000,18484.000000,138.000000,3.714000,0.999000,1.000000,1.000000,1.000000,1.000000